Repository FRONTENDBOOTCAMP-13th/8ollowme, pull requests merged in 2025-03, with the labels that each got.

#20 ✨ feat: add SVG icon assets
  src/assets/icons/4G.svg
  src/assets/icons/Edit.svg
  src/assets/icons/app.svg
  src/assets/icons/back.svg
  src/assets/icons/battery.svg
  src/assets/icons/bookmark-false.svg
  src/assets/icons/bookmark.svg
  src/assets/icons/bubble.svg
  src/assets/icons/call-bw.svg
  src/assets/icons/call.svg
  src/assets/icons/car.svg
  src/assets/icons/check.svg
  src/assets/icons/circle-plus-black.svg
  src/assets/icons/circle-plus-white.svg
  src/assets/icons/close-circle.svg
  src/assets/icons/close.svg
  src/assets/icons/cut.svg
  src/assets/icons/date.svg
  src/assets/icons/doc.svg
  src/assets/icons/down.svg
  src/assets/icons/downArrow.svg
  src/assets/icons/eye-black.svg
  src/assets/icons/gift.svg
  src/assets/icons/gps.svg
  src/assets/icons/hambuger.svg
  src/assets/icons/heart.svg
  src/assets/icons/hospital.svg
  src/assets/icons/info.svg
  src/assets/icons/left.svg
  src/assets/icons/location.svg
  src/assets/icons/map.svg
  src/assets/icons/meal.svg
  src/assets/icons/minus.svg
  src/assets/icons/mission.svg
  src/assets/icons/my.svg
  src/assets/icons/paper.svg
  src/assets/icons/pencil.svg
  src/assets/icons/photo.svg
  src/assets/icons/picture.svg
  src/assets/icons/plus.svg
  src/assets/icons/position.svg
  src/assets/icons/question.svg
  src/assets/icons/recipe-footer.svg
  src/assets/icons/save.svg
  src/assets/icons/share.svg
  src/assets/icons/subway.svg
  src/assets/icons/ticket.svg
  src/assets/icons/up.svg
  src/assets/icons/upArrow.svg
Labels: 🚀 enhancement

#22 visit component 제작
  src/assets/icons/photo-b.svg
  src/components/visit/visit.html
  src/style.css
Labels: 🚀 enhancement

#33 Feat/common component
  src/assets/button/button-down.svg
  src/assets/button/button-left.svg
  src/assets/icon/4g.svg
  src/assets/icon/battery.svg
  src/assets/icon/bling.svg
  src/assets/icon/call.svg
  src/assets/icon/car.svg
  src/assets/icon/down.svg
  src/assets/icon/edit.svg
  src/assets/icon/gps.svg
  src/assets/icon/like.svg
  src/assets/icon/location.svg
  src/assets/icon/lte-battery.svg
  src/assets/icon/map.svg
  src/assets/icon/menu.svg
  src/assets/icon/mission.svg
  src/assets/icon/my.svg
  src/assets/icon/pencil.svg
  src/assets/icon/plus.svg
  src/assets/icon/position.svg
  src/assets/icon/save.svg
  src/assets/icon/selected.svg
  src/assets/icon/share.svg
  src/assets/icon/start.svg
  src/assets/icon/subway.svg
  src/assets/icon/time-gps.svg
  src/components/common/common.html
  src/components/common/components/bottom-bar.html
  src/components/common/components/card.html
  src/components/common/components/place-selector.html
  src/components/common/components/profile.html
  src/components/common/components/top-bar.html
  src/components/common/components/type-selector.html
  src/style.css
  vite.config.js
Labels: 🚀 enhancement, 🔥 priority : 0

#41 visit page layout
  src/components/visit/photo.js
  src/components/visit/review-w-guidelines.html
  src/pages/visit-bakery.html
  src/pages/visit.html
  src/style.css
  vite.config.js
Labels: 📖 documentation, 🚀 enhancement, 🔥 priority : 0

#45 Reserve component
  src/assets/icons/call-b.svg
  src/assets/icons/date-blue.svg
  src/assets/icons/down-b.svg
  src/assets/icons/spoon.svg
  src/assets/images/cherry-blossoms-poster.png
  src/components/reserve/reserve.html
  src/style.css
Labels: 🚀 enhancement

#68 Refactor/pages reserve& visit & order
  src/pages/order/order.html
  src/pages/reserve-page/reserve.html
  src/pages/visit/visit-2.html
  src/pages/visit/visit-3.html
  src/style.css
Labels: 🔧 refactor

#73 71 login follow blossom etc
  src/pages/blossom-spots/blossom-spots-1.html
  src/pages/blossom-spots/blossom-spots-2.html
  src/pages/login-page/login-1.html
  src/pages/login-page/login-2.html
  src/pages/login-page/login-3.html
  src/pages/setting-page/setting-1.html
  src/pages/setting-page/setting-2.html
  src/pages/setting-page/setting-3.html
Labels: 🐛 bug, 🔧 refactor

#93 88 refactor login page
  README.md
  image-1.png
  index.html
  src/assets/profile/doul_profile.png
  src/pages/blossom-spots/blossom-spots-2.html
  src/pages/follow-page/follow-1.html
  src/pages/follow-page/follow-2.html
  src/pages/follow-page/follow-doul.html
  src/pages/follow-page/follow-dowool.html
  src/pages/login-page/login-1.html
  src/pages/login-page/login-2.html
  src/pages/login-page/login-3.html
  src/pages/setting-page/setting-1.html
  src/style.css
Labels: 📖 documentation, 🚀 enhancement

#100 Refacto/rvisit component
  src/components/visit/review-w-g-bakery.html
  src/components/visit/review-w-guidelines.html
Labels: 🔧 refactor
